# Generated by Django 3.2.3 on 2021-05-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
